#!/usr/bin/env python3
"""Generate a fake SceneExplorer library (Qt-compatible db.sqlite3 + .scexd + thumbs + tiny videos).

Everything is synthetic, so the WebUI can be developed, screenshotted and tested without touching a real library.

  python3 make_dummy_library.py OUTDIR [--count 120]
  eval "$(python3 make_dummy_library.py OUTDIR --env)"   # prints SE_DB_DIR / SE_DOC_FILE exports
"""
import argparse, os, random, shutil, sqlite3, subprocess, sys, uuid
from PIL import Image, ImageDraw, ImageFont

FONT = "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc"
DBID = "dummy-dbid-0001"
W, H = 187, 140
WORDS_JA = ["夏の海", "運動会", "料理教室", "京都旅行", "花火大会", "発表会", "ドライブ", "誕生日会", "キャンプ", "卒業式", "紅葉狩り", "初詣"]
WORDS_EN = ["Holiday", "Birthday_Party", "Lecture", "Concert_Live", "Trailer", "Hiking", "Festival", "Sample_Clip", "Timelapse"]
EXTS = ["mp4", "mkv", "mov", "webm"]
TAGS = [("旅行", "りょこう"), ("家族", "かぞく"), ("料理", "りょうり"), ("イベント", "いべんと")]


def make_thumb(path, seed, label):
    r = random.Random(seed)
    a = [r.randint(30, 110) for _ in range(3)]; b = [r.randint(60, 200) for _ in range(3)]
    im = Image.new("RGB", (W, H)); px = im.load()
    for y in range(H):
        for x in range(W):
            t = (x / W + y / H) / 2
            px[x, y] = tuple(int(a[i] + (b[i] - a[i]) * t) for i in range(3))
    d = ImageDraw.Draw(im)
    d.text((W // 2, H // 2), label, font=ImageFont.truetype(FONT, 28), fill="white", anchor="mm")
    im.save(path, quality=80)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("out"); ap.add_argument("--count", type=int, default=120); ap.add_argument("--env", action="store_true")
    ap.add_argument("--qt-default-size", action="store_true", help="240x180 thumbnails named <id>-<n>.jpg, like the Qt app's default setting")
    a = ap.parse_args()
    out = os.path.abspath(a.out)
    global W, H
    if a.qt_default_size:
        W, H = 240, 180
    dbdir, thumbs = os.path.join(out, "db"), os.path.join(out, "db", "thumbs")
    doc = os.path.join(out, "dummy.scexd")
    if a.env:
        print(f'export SE_DB_DIR="{dbdir}" SE_DOC_FILE="{doc}"'); return
    shutil.rmtree(out, ignore_errors=True)
    dirs = [os.path.join(out, n) + "/" for n in ("movies", "anime", "archive")]
    for d in dirs + [dirs[0] + "sub/"]:
        os.makedirs(d)
    os.makedirs(thumbs)
    open(os.path.join(out, ".dummy-library"), "w").write("generated by make_dummy_library.py\n")

    sample = os.path.join(out, "sample.mp4")
    try:
        subprocess.run(["ffmpeg", "-v", "error", "-y", "-f", "lavfi", "-i", "testsrc=duration=8:size=320x240:rate=25",
                        "-f", "lavfi", "-i", "sine=duration=8", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac",
                        "-movflags", "+faststart", sample], check=True)
    except (OSError, subprocess.CalledProcessError):
        sample = None
        print("ffmpeg not available: video files will be tiny non-playable stubs", file=sys.stderr)

    rnd = random.Random(42)
    lib = sqlite3.connect(os.path.join(dbdir, "db.sqlite3"))
    lib.executescript("""CREATE TABLE DbInfo(id INTEGER PRIMARY KEY, dbid TEXT, version INT);
      CREATE TABLE FileInfo(id INTEGER PRIMARY KEY, directory TEXT, name TEXT, size INT NOT NULL DEFAULT 0,
        ctime INT NOT NULL DEFAULT 0, wtime INT NOT NULL DEFAULT 0, salient TEXT, thumbid TEXT,
        duration INT NOT NULL DEFAULT 0, format TEXT, bitrate INT NOT NULL DEFAULT 0, vcodec TEXT, acodec TEXT,
        vwidth INT NOT NULL DEFAULT 0, vheight INT NOT NULL DEFAULT 0, thumbext, fps, recordversion, url, memo);
      CREATE UNIQUE INDEX idx_directoryname ON FileInfo(directory,name);""")
    lib.execute("INSERT INTO DbInfo VALUES (1, ?, 4)", (DBID,))
    doc = sqlite3.connect(doc)
    doc.executescript("""CREATE TABLE Directories(id INTEGER NOT NULL PRIMARY KEY, directory TEXT, selected INT, checked INT, displaytext);
      CREATE TABLE Access(id INTEGER NOT NULL, opencount INT NOT NULL DEFAULT 0, lastaccess INT, dbid TEXT NOT NULL);
      CREATE UNIQUE INDEX idx_Access_id_dbid ON Access(id,dbid);
      CREATE TABLE Tag(tagid INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, tag, yomi, dbid TEXT NOT NULL, selected INT NOT NULL DEFAULT 0, checked INT NOT NULL DEFAULT 0);
      CREATE UNIQUE INDEX idx_Tag_tagid_dbid ON Tag(tagid,dbid);
      CREATE TABLE Tagged(id INTEGER NOT NULL, tagid INTEGER NOT NULL, dbid TEXT NOT NULL);
      CREATE UNIQUE INDEX idx_Tagged_id_tagid_dbid ON Tagged(id,tagid,dbid);""")
    for i, d in enumerate(dirs, 1):
        doc.execute("INSERT INTO Directories VALUES (?,?,0,0,?)", (i, d, "アニメ" if i == 2 else None))
    for t, y in TAGS:
        doc.execute("INSERT INTO Tag(tag,yomi,dbid) VALUES (?,?,?)", (t, y, DBID))

    for i in range(1, a.count + 1):
        d = rnd.choice(dirs + [dirs[0] + "sub/"])
        name = f"{rnd.choice(WORDS_JA + WORDS_EN)} {i:03d}.{rnd.choice(EXTS)}"
        if i % 17 == 0:
            name = "とても長いファイル名のサンプル動画 " + "long_title_" * 6 + f"{i:03d}.mp4"
        tid = str(uuid.UUID(int=rnd.getrandbits(128)))
        n = rnd.choice([3, 5, 10])
        for k in range(1, n + 1):
            make_thumb(os.path.join(thumbs, f"{tid}-{k}.jpg" if a.qt_default_size else f"{tid}-{W}x{H}-{k}.jpg"), i * 100 + k, f"{i}-{k}")
        dur = rnd.choice([12, 95, 600, 1800, 5025, 7300]) + rnd.random()
        lib.execute("INSERT INTO FileInfo(id,directory,name,size,ctime,wtime,thumbid,duration,format,bitrate,vcodec,acodec,vwidth,vheight,thumbext,fps) "
                    "VALUES (?,?,?,?,?,?,?,?,'mp4',?,?,?,?,?,'jpg',?)",
                    (i, d, name, rnd.randint(50_000_000, 6_000_000_000), 1600000000 + i, 1600000000 + rnd.randint(0, 100_000_000),
                     tid, dur, rnd.randint(500_000, 8_000_000), rnd.choice(["h264", "hevc", "vp9"]), "aac",
                     *rnd.choice([(1920, 1080), (1280, 720), (3840, 2160), (640, 480)]), rnd.choice([24.0, 29.97, 30.0, 60.0])))
        if i % 11 != 0:  # every 11th video is "missing" from disk
            f = os.path.join(d, name)
            if sample: shutil.copyfile(sample, f)
            else: open(f, "wb").write(b"stub")
        for tagid in range(1, len(TAGS) + 1):
            if rnd.random() < 0.25:
                doc.execute("INSERT INTO Tagged VALUES (?,?,?)", (i, tagid, DBID))
        if rnd.random() < 0.4:
            doc.execute("INSERT INTO Access VALUES (?,?,?,?)", (i, rnd.randint(1, 20), 1700000000 + rnd.randint(0, 9_000_000), DBID))
    lib.commit(); doc.commit(); lib.close(); doc.close()
    print(f"dummy library: {a.count} videos in {out}", file=sys.stderr)


if __name__ == "__main__":
    main()
